"""added column for cognito

Revision ID: ac1a3e5c37c7
Revises: b0a16b200e25
Create Date: 2022-07-14 16:49:30.755444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1a3e5c37c7'
down_revision = 'b0a16b200e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cognito', sa.Boolean(), nullable=True))
    op.alter_column('book', 'book_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('library', sa.Column('cognito', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'cognito')
    op.alter_column('book', 'book_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('book', 'cognito')
    # ### end Alembic commands ###
