"""column for book image

Revision ID: b0a16b200e25
Revises: f5d2175e4930
Create Date: 2022-07-10 18:20:33.461322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a16b200e25'
down_revision = 'f5d2175e4930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'book_image')
    # ### end Alembic commands ###
