"""added file upload data

Revision ID: edf43332d3cc
Revises: eb1214e164b5
Create Date: 2022-06-16 01:35:08.253967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf43332d3cc'
down_revision = 'eb1214e164b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prof_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'prof_data')
    # ### end Alembic commands ###
